import sys
import os

block_cipher = None

backend_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    [os.path.join(backend_dir, 'app.py')],
    pathex=[backend_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        'classes',
        'classes.account_manager',
        'classes.roblox_api',
        'classes.encryption',
        'classes.icon_cache',
        'classes.roblox_installer',
        'classes.updater',
        'classes.auto_rejoin',
        'classes.browser_extensions',
        'classes.fastflags',
        'classes.roblox_global_settings',
        'classes.auto_arranger',
        'classes.headless_manager',
        'classes.anti_afk',
        'classes.roblox_swap',
        'classes.webhook_manager',
        'classes.chromium_downloader',
        'classes.roblox_app_storage',
        'classes.roblox_ixp_settings',
        'utils',
        'utils.paths',
        'utils.error_detector',
        'utils.cleanup',
        'psutil',
        'PIL',
        'PIL.ImageGrab',
        'flask',
        'flask_cors',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.by',
        'selenium.common.exceptions',
        'selenium.webdriver.firefox.service',
        'selenium.webdriver.firefox.options',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'webdriver_manager.firefox',
        'requests',
        'requests.adapters',
        'urllib3',
        'urllib3.util.retry',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Cipher.AES',
        'Crypto.Random',
        'Crypto.Protocol',
        'Crypto.Protocol.KDF',
        'xml.etree.ElementTree',
        'ipaddress',
        'dataclasses',
        'ctypes',
        'ctypes.wintypes',
        'hashlib',
        'hmac',
        'secrets',
        'uuid',
        'csv',
        'base64',
        'zipfile',
        'tempfile',
        'shutil',
        'pathlib',
        'threading',
        'platform',
        'subprocess',
        'json',
        're',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(backend_dir, '..', 'src-tauri', 'icons', 'icon.ico'),
    version=os.path.join(backend_dir, 'version_info.txt'),
)
