blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/SpMTxg8YjJ
    about: Ask questions, get help, or chat with the community on our official Discord server.
